#!/bin/bash

# Easy Attack Scenario
# Attacker repeatedly requests for 404 paths while normal users request normal pages

echo "Getting attack properties for easy scenario attack..."

if [ -f /tmp/micro_soc_state.env ]; then
    # Load attack properties generated by reset()
    source /tmp/micro_soc_state.env
else
    # Sourcing should work, it will, it does....
    # But what if it doesn't? So, uhh... generating em just in case...
    ATTACKER_IP="$((RANDOM % 255 + 1)).$((RANDOM % 255)).$((RANDOM % 255)).$((RANDOM % 255))"
    NORMAL_IPS=("$((RANDOM % 255 + 1)).$((RANDOM % 255)).$((RANDOM % 255)).$((RANDOM % 255))" "$((RANDOM % 255 + 1)).$((RANDOM % 255)).$((RANDOM % 255)).$((RANDOM % 255))")
fi

COUNTER=0
NORMAL_PATHS=("/" "/index.html" "/about" "/contact" "/products" "/favicon.ico")

echo "Starting easy scenario attack..."

while true; do
    # Attacker scans of suspicious paths (404s with Attacker IP)
    curl -s -H "X-Forwarded-For: $ATTACKER_IP" http://localhost/admin > /dev/null
    curl -s -H "X-Forwarded-For: $ATTACKER_IP" http://localhost/.env > /dev/null
    curl -s -H "X-Forwarded-For: $ATTACKER_IP" http://localhost/wp-login.php > /dev/null
    curl -s -H "X-Forwarded-For: $ATTACKER_IP" http://localhost/phpmyadmin > /dev/null
    curl -s -H "X-Forwarded-For: $ATTACKER_IP" http://localhost/.git/config > /dev/null

    COUNTER=$((COUNTER + 1))

    # Every alternate loop include 1-2 normal user requests (To simulate a mix of normal traffic)
    if [ $((COUNTER % 2)) -eq 0 ]; then
        IP=${NORMAL_IPS[$((RANDOM % ${#NORMAL_IPS[@]}))]}
        PATH_=${NORMAL_PATHS[$((RANDOM % ${#NORMAL_PATHS[@]}))]}
        curl -s -H "X-Forwarded-For: $IP" "http://localhost${PATH_}" > /dev/null

        sleep 0.1
        
        IP2=${NORMAL_IPS[$((RANDOM % ${#NORMAL_IPS[@]}))]}
        PATH2=${NORMAL_PATHS[$((RANDOM % ${#NORMAL_PATHS[@]}))]}
        curl -s -H "X-Forwarded-For: $IP2" "http://localhost${PATH2}" > /dev/null
    fi

    sleep 0.3
done
