#!/bin/bash
# Medium Attack Scenario 
# Brute force attack for authenticating via SSH

echo "Getting attack properties for medium scenario attack..."

if [ -f /tmp/micro_soc_state.env ]; then
    # Load attack properties generated by reset()
    source /tmp/micro_soc_state.env
else
    # Generating the attack properties just in case the env file is missing)
    ATTACKER_IP="$((RANDOM % 255 + 1)).$((RANDOM % 255)).$((RANDOM % 255)).$((RANDOM % 255))"
    ADMIN_IP="$((RANDOM % 255 + 1)).$((RANDOM % 255)).$((RANDOM % 255)).$((RANDOM % 255))"
fi

COUNTER=2
PORTS=(51234 52891 53007 54321 55102 56777 57438)
USERS=("root" "admin" "ubuntu" "pi" "user" "deploy" "git")

echo "Starting medium scenario attack (From $ATTACKER_IP, with Admin IP set to $ADMIN_IP)..."

while true; do
    # 5-8 failed authentication attempts per loop
    BURST=$((RANDOM % 4 + 5))
    for i in $(seq 1 $BURST); do
        USER=${USERS[$((RANDOM % ${#USERS[@]}))]}
        PORT=${PORTS[$((RANDOM % ${#PORTS[@]}))]}
        echo "$(date '+%b %d %H:%M:%S') myhost sshd[$((RANDOM % 9000 + 1000))]: Failed password for $USER from $ATTACKER_IP port $PORT ssh2" >> /var/log/auth.log
        sleep 0.2
    done

    COUNTER=$((COUNTER + 1))

    # Every 3 loops add an admin login from the admin IP
    if [ $((COUNTER % 3)) -eq 0 ]; then
        echo "$(date '+%b %d %H:%M:%S') myhost sshd[2200]: Accepted password for admin from $ADMIN_IP port 22 ssh2" >> /var/log/auth.log
    fi

    sleep 3
done
